#!/bin/bash

result=0

for ((i = 1 ; i <= $# ; i++)); do
        if [ -d "${!i}" ]; then
                rm "${!i}"/*.{bak,tmp,backup}
                echo ".bak, .tmp и .backup файлы успешно удалены из директории ${!i}"
        else
                echo "Директория ${!i} не найдена"
                result=$((result + 1))
        fi
done

exit $result



